### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by MickMelon** [MickMelon/FRAGS#1]
Need to decide on the database implementation.

**Comment by mrredcon** [comment]
I've created an EF CharacterProvider in the [`efcore`](https://github.com/MickMelon/FRAGS/tree/efcore) branch.

**Comment by mrredcon** [comment]
RavenDB CharacterProvider also functional.
I deleted the efcore branch as I've made changes that affects both EF and RavenDB in the ravendb branch

**Comment by mrredcon** [comment]
decided on EF
